###
POST https://pdp-todo-app-dev.betty.app/api/runtime/bb79b5f831cb4120a2352e3a07aad4dc
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
    allTask {
        results {
            id
        }
    }
}



  