import { LOGIN_MUTATION, REFRESH_MUTATION } from "./login";
import {
  TODO_CREATE_MUTATION,
  TODO_DELETE_MUTATION,
  TODO_UPDATE_MUTATION,
  TODOS_QUERY,
} from "./todos";
import { SIGNUP_MUTATION } from "./signup";

export {
  LOGIN_MUTATION,
  REFRESH_MUTATION,
  TODO_CREATE_MUTATION,
  TODO_DELETE_MUTATION,
  TODO_UPDATE_MUTATION,
  TODOS_QUERY,
  SIGNUP_MUTATION,
};
